import { existsSync, mkdirSync, watch } from 'node:fs'
import { join } from 'node:path'
import { parseArgs } from 'node:util'
import { $ } from 'bun'

const SRC = 'src'
const STYLES_SRC = `${SRC}/styles.src.css`
const STYLES_OUT = 'styles.css'
const PLUGIN_ID = 'life-tracker-base-view'
const FILES_TO_COPY = ['main.js', 'manifest.json', 'styles.css']
const BANNER = `/*
THIS IS A GENERATED/BUNDLED FILE BY BUN.
If you want to view the source, please visit the github repository of this plugin.
*/
`

const { values } = parseArgs({
    args: Bun.argv,
    options: {
        prod: {
            type: 'boolean',
            default: false
        }
    },
    strict: true,
    allowPositionals: true
})
const isProd = values.prod

async function buildStyles() {
    console.log('Building Tailwind CSS...')
    try {
        const minifyFlag = isProd ? '--minify' : ''
        await $`bunx @tailwindcss/cli -i ${STYLES_SRC} -o ${STYLES_OUT} ${minifyFlag}`.quiet()
        console.log('CSS build succeeded.')
    } catch (error) {
        console.error('CSS build failed:', error)
        if (isProd) {
            throw error
        }
    }
}

async function buildJs() {
    console.log(`Building plugin in ${isProd ? 'production' : 'development'} mode...`)
    const { success, logs } = await Bun.build({
        banner: BANNER,
        entrypoints: [`${SRC}/main.ts`],
        outdir: '.',
        external: [
            'obsidian',
            'electron',
            '@codemirror/autocomplete',
            '@codemirror/collab',
            '@codemirror/commands',
            '@codemirror/language',
            '@codemirror/lint',
            '@codemirror/search',
            '@codemirror/state',
            '@codemirror/view',
            '@lezer/common',
            '@lezer/highlight',
            '@lezer/lr'
        ],
        format: 'cjs',
        target: 'node',
        minify: isProd,
        sourcemap: isProd ? false : 'inline',
        throw: isProd
    })
    if (success) {
        console.log('JS build succeeded.')
    } else {
        console.error('JS build failed.')
        console.error(logs)
    }
}

async function copyToVault(): Promise<void> {
    const vaultPath = process.env['OBSIDIAN_VAULT_LOCATION']
    if (!vaultPath) {
        console.log(
            'Tip: Set OBSIDIAN_VAULT_LOCATION to auto-copy the plugin to your vault after each build.'
        )
        return
    }

    const pluginDir = join(vaultPath, '.obsidian', 'plugins', PLUGIN_ID)

    if (!existsSync(pluginDir)) {
        console.log(`Creating plugin directory: ${pluginDir}`)
        mkdirSync(pluginDir, { recursive: true })
    }

    console.log(`Copying files to ${pluginDir}...`)

    for (const file of FILES_TO_COPY) {
        if (existsSync(file)) {
            const dest = join(pluginDir, file)
            await Bun.write(dest, Bun.file(file))
            console.log(`  ✓ ${file}`)
        }
    }

    // Create .hotreload file for hot-reload plugin support
    await Bun.write(join(pluginDir, '.hotreload'), '')
    console.log('  ✓ .hotreload')
}

async function build(): Promise<void> {
    await Promise.all([buildJs(), buildStyles()])

    if (!isProd) {
        await copyToVault()
    }
}

await build()

if (!isProd) {
    watch(`${SRC}`, { recursive: true }, async (event, path) => {
        console.log(`Detected ${event} in ${SRC}/${path}`)
        await build()
    })
}
