import { watch } from 'node:fs'
import { parseArgs } from 'node:util'
import { $ } from 'bun'

const SRC = 'src'
const STYLES_SRC = `${SRC}/styles.src.css`
const STYLES_OUT = 'styles.css'
const BANNER = `/*
THIS IS A GENERATED/BUNDLED FILE BY BUN.
If you want to view the source, please visit the github repository of this plugin.
*/
`

const { values } = parseArgs({
    args: Bun.argv,
    options: {
        prod: {
            type: 'boolean',
            default: false
        }
    },
    strict: true,
    allowPositionals: true
})
const isProd = values.prod

async function buildStyles() {
    console.log('Building Tailwind CSS...')
    try {
        const minifyFlag = isProd ? '--minify' : ''
        await $`bunx @tailwindcss/cli -i ${STYLES_SRC} -o ${STYLES_OUT} ${minifyFlag}`.quiet()
        console.log('CSS build succeeded.')
    } catch (error) {
        console.error('CSS build failed:', error)
        if (isProd) {
            throw error
        }
    }
}

async function buildJs() {
    console.log(`Building plugin in ${isProd ? 'production' : 'development'} mode...`)
    const { success, logs } = await Bun.build({
        banner: BANNER,
        entrypoints: [`${SRC}/main.ts`],
        outdir: '.',
        external: [
            'obsidian',
            'electron',
            '@codemirror/autocomplete',
            '@codemirror/collab',
            '@codemirror/commands',
            '@codemirror/language',
            '@codemirror/lint',
            '@codemirror/search',
            '@codemirror/state',
            '@codemirror/view',
            '@lezer/common',
            '@lezer/highlight',
            '@lezer/lr'
        ],
        format: 'cjs',
        target: 'node',
        minify: isProd,
        sourcemap: isProd ? false : 'inline',
        throw: isProd
    })
    if (success) {
        console.log('JS build succeeded.')
    } else {
        console.error('JS build failed.')
        console.error(logs)
    }
}

async function build() {
    await Promise.all([buildJs(), buildStyles()])
}

await build()

if (!isProd) {
    watch(`${SRC}`, { recursive: true }, async (event, path) => {
        console.log(`Detected ${event} in ${SRC}/${path}`)
        await build()
    })
}
